### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-github#57]
This is my working checklist for tasks to complete before we ship 1.0.0.

Features:
- [x] Implement repository search API (#56)
- [x] Support stream polling
- [x] Support rate-limiting and quota queries
- [x] Distinguish between pull requests and issues (#60)
- [x] Support listing issues regardless of their state (#59)

Tasks:
- [x] Paginate correctly (#46)
- [x] Check all interfaces for consistency
- [x] ocamldoc
- [x] Write README with up-to-date API support info
- [x] Request contributor/user feedback on the large number of changes in 1.0.0
- [x] Transfer repository to an organization
- [x] "Transfer" "maintainership" to @dsheets
- [x] A simple test case for the JavaScript version

Have I missed anything?

**Comment by avsm** [comment]
- [ ] Take maintainer :)

**Comment by avsm** [comment]
A simple test case for the JavaScript version would be useful, although perhaps not entirely related.

**Comment by dsheets** [comment]
- [ ] A simple test case for the JavaScript version would be useful, although perhaps not entirely related.

**Comment by michipili** [comment]
Maybe #59 and #60?

**Comment by dsheets** [comment]
Great issues! I've added them to the list and will fix them today.

**Comment by dsheets** [comment]
Oops. I see you've already fixed #59 with #62.

**Comment by dsheets** [comment]
@avsm could you review/merge #58 and then transfer this repository to an organization, give me admin rights, or both?

**Comment by avsm** [comment]
yep

**Comment by avsm** [comment]
Repository transfer to mirage/ has now been executed.

**Comment by michipili** [comment]
@avsm What are the concrete consequences for contributors? It looks like issues etc. followed, so am I right thinking I should only update the `remote` references in my local clones?

**Comment by avsm** [comment]
@michipili that's right -- all state has just shifted over to `mirage/ocaml-github`, and I've reforked my personal repo from that.  The new org means that we can have more maintainers like @dsheets now, and not block on me.  Let me know if you run into any other issues with the shift!

**Comment by michipili** [comment]
@avsm Everything looks great, thanks! :)

**Comment by dsheets** [comment]
All checklist tasks have now been completed. After #82 is merged, I will release 1.0.0.

**Comment by michipili** [comment]
Thanks for the great work @dsheets!
